Update rules_foreign_cc (#1511)
# Description

Bazel build on master fails with:
```
+ .../bin/external/bazel_tools/tools/python/py3wrapper.sh ./configure.py --bootstrap
Traceback (most recent call last):
  File ".../execroot/libsbp/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 26, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

Updating to a newer version of `rules_foreign_cc` fixes the problem.

# API compatibility

No,

# JIRA Reference

https://swift-nav.atlassian.net/browse/AP-4662