docker: sync with github actions [DEVINFRA-486]
The libsbp-build image has gotten out of sync with GitHub actions such
as Java and JavaScript where no longer passing when building locally.

Update the libsbp-bulid image so it more closely matches the GitHub
actions environment.

Specifically Java was failing with the following error:

```
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Process 'Gradle Test Executor 12' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 12' finished with non-zero exit value 134
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
...
```

JavaScript was failing with the following error:

```
  3019 passing (14s)
  1 failing

  1) dispatcher
       should read stream of bytes and dispatch callback for one valid message, ignore corrupt preamble:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/mnt/workspace/javascript/tests/test_dispatch.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```