Bump docker image used for rust build to 1.65 (#1396)
This solves the following error message:

error: failed to compile `sbp2json v5.0.4-alpha (https://github.com/swift-nav/libsbp.git#b9860dc1)`, intermediate artifacts can be found at `/tmp/cargo-installVrmlST`

Caused by:
  package `regex v1.10.2` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.61.0